services:
  - type: web
    name: bee-keeps
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT "app:create_app()" --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.13.0
